name: Publish docker image to docker hub
on:
  release:
    types:
      - published

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Get dependencies
        run: go mod download

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: Get release tags
        id: extractversion
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            cikupin/testing-github-action:${{ steps.extractversion.outputs.tag }}
            cikupin/testing-github-action:latest
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
