name: 'Ansible job matrix'

on: workflow_dispatch

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print readme.txt
        run: |
          cat ./_ansible/readme.txt

  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        instances:
          - instance-1
          - instance-2
          - instance-3
          - instance-4 # test failed job in parallel task
    needs:
      - init

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run ansible ${{ matrix.instances }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yaml
          directory: ./_ansible/${{ matrix.instances }}

  finisher:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Print finish
        run: |
          echo "Process finised"

