name: 'Ansible job matrix'

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instances:
          - instance-1
          - instance-2
          - instance-3

    steps:
      - name: Run ansible ${{ matrix.node }}
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yaml
          directory: ./_ansible/${{ matrix.node }}
